import * as React from 'react'
import { Box } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import { useAuthStore } from '@/store/auth'
import CONFIG from '@/constants/config'

const Main = () => {
	const { token } = useAuthStore()

	return (
		<Box
			sx={{
				display: 'flex',
				flexDirection: 'column',
				height: '100vh',
				width: '100vw',
			}}
		>
			<Head>
				<title>Create NEXT App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box
				component="main"
				sx={{ flexGrow: 1, width: `calc(100% - ${CONFIG.DRAWER_WIDTH}px)` }}
			>
				<p style={{ overflowWrap: 'break-word' }}>LoggedIn as: {token}</p>
			</Box>

			<Box
				component="footer"
				sx={{ zIndex: 'modal', bgcolor: 'background.default', p: 2 }}
			>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</Box>
		</Box>
	)
}

// export async function getStaticProps() {
// 	return await preFetchData('https://jsonplaceholder.typicode.com/posts')
// }

export default Main
